DoSomething/tower

group_vars/staging/app-environment.yml

Sets up RDS DB access on Staging.

Sets up RDS access.

---

requirements.yml
roles/dosomething.base/meta/.galaxy_install_info
roles/dosomething.base/tasks/setup-user.yml
roles/dosomething.dosomething-dev/meta/.galaxy_install_info
roles/dosomething.dosomething/meta/.galaxy_install_info
roles/dosomething.dosomething/tasks/main.yml
roles/dosomething.redis/README.md
roles/dosomething.redis/defaults/main.yml
roles/dosomething.redis/handlers/main.yml
roles/dosomething.redis/meta/.galaxy_install_info
roles/dosomething.redis/meta/main.yml
roles/dosomething.redis/tasks/main.yml
roles/dosomething.redis/vars/main.yml
roles/dosomething.search/meta/.galaxy_install_info
roles/dosomething.web/meta/.galaxy_install_info
staging.yml

- Fixes env issues during cap deployment
- Moves redis-server to the separate role

Update roles to the last version.

---

roles/dosomething.base/tasks/install-common-tools.yml

@sergii-tkachenko Look okay to you?

Updating base tools per host to be a bit more comprehensive.

---

group_vars/international-production/settings-search.yml
group_vars/international-production/settings-web.yml

Changes to international production:
- Add intl solr cores
- Turn off PHP errors

International Prod: search and display_errors.

---

group_vars/tag_Role_Drupal-WebApp/app-environment.yml

Intended to fix "user login not found" error.

Adds DS_SECURE_PORT variable to Drupal Prod.

---

group_vars/international-production/main.yml
group_vars/staging/main.yml
group_vars/tag_Role_Drupal-WebApp/main.yml
roles/dosomething.base/meta/.galaxy_install_info
roles/dosomething.dosomething-dev/meta/.galaxy_install_info
roles/dosomething.dosomething/defaults/main.yml
roles/dosomething.dosomething/files/status.php
roles/dosomething.dosomething/meta/.galaxy_install_info
roles/dosomething.dosomething/tasks/app.yml
roles/dosomething.dosomething/vars/main.yml
roles/dosomething.redis/meta/.galaxy_install_info
roles/dosomething.search/meta/.galaxy_install_info
roles/dosomething.web/meta/.galaxy_install_info

Create shared folder with status.php on staging, intl and prod.

---

group_vars/international-production/main.yml
group_vars/staging/main.yml
group_vars/tag_Role_Drupal-WebApp/main.yml
roles/dosomething.base/meta/.galaxy_install_info
roles/dosomething.dosomething-dev/meta/.galaxy_install_info
roles/dosomething.dosomething/meta/.galaxy_install_info
roles/dosomething.dosomething/vars/main.yml
roles/dosomething.redis/meta/.galaxy_install_info
roles/dosomething.search/meta/.galaxy_install_info
roles/dosomething.web/meta/.galaxy_install_info

See DoSomething/ansible-dosomething#24.

Setup `app_shared` variable.

---

roles/dosomething.base/meta/.galaxy_install_info
roles/dosomething.dosomething-dev/meta/.galaxy_install_info
roles/dosomething.dosomething/meta/.galaxy_install_info
roles/dosomething.dosomething/templates/nginx/app.j2
roles/dosomething.redis/meta/.galaxy_install_info
roles/dosomething.search/meta/.galaxy_install_info
roles/dosomething.web/meta/.galaxy_install_info

Update roles: always pass Nginx HTTPS fastcgi param.

---

group_vars/tag_Role_Drupal-WebApp/main.yml
roles/dosomething.base/meta/.galaxy_install_info
roles/dosomething.dosomething-dev/meta/.galaxy_install_info
roles/dosomething.dosomething/defaults/main.yml
roles/dosomething.dosomething/meta/.galaxy_install_info
roles/dosomething.dosomething/templates/nginx/app.j2
roles/dosomething.redis/meta/.galaxy_install_info
roles/dosomething.search/meta/.galaxy_install_info
roles/dosomething.web/meta/.galaxy_install_info

Production: Always pass HTTPS fastcgi_param = on.

---

production.yml

Production: mount shared folder experiment.

---

production.yml

See https://52.0.184.104/#/jobs/217/stdout

Fix ERROR: mount is not a legal parameter of an Ansible Play.

---

production.yml

See https://52.0.184.104/#/jobs/220

Production mount: use sudo.

---

production.yml

See https://52.0.184.104/#/jobs/222
http://askubuntu.com/questions/525243/why-do-i-get-wrong-fs-type-bad-option-bad-superblock-error

Production: Install nfs-common.

---

production.yml

Reverts DoSomething/tower#36
See https://52.0.184.104/#/jobs/228
mount: only root can do that

Revert "Production: mount shared folder as app user."

---

group_vars/tag_Role_Drupal-WebApp/app-environment.yml

See https://52.0.184.104/#/jobs/235/stdout

Fix an error in production app environment.

---

group_vars/international-production/app-environment.yml
group_vars/staging/app-environment.yml
group_vars/tag_Role_Drupal-WebApp/app-environment.yml
roles/dosomething.base/meta/.galaxy_install_info
roles/dosomething.dosomething-dev/meta/.galaxy_install_info
roles/dosomething.dosomething/meta/.galaxy_install_info
roles/dosomething.dosomething/tasks/configure-env.yml
roles/dosomething.redis/meta/.galaxy_install_info
roles/dosomething.search/meta/.galaxy_install_info
roles/dosomething.web/meta/.galaxy_install_info

See DoSomething/ansible-dosomething#29.

Rename app environment.

---

group_vars/international-production/app-environment.yml
group_vars/international-production/main.yml

Configures International Production variables.

Setup International Production.

---

group_vars/tag_Role_Drupal-WebApp/settings-web.yml

CC @mshmsh5000 @blisteringherb

Tweaks PHP FPM server pool.

---

group_vars/tag_Role_Drupal-WebApp/settings-web.yml

Prod: Bring pm.max_children down to 16.

---

.gitignore
Vagrantfile
roles/requirements.yml

See Tower 2.2, frame 13:00:
http://www.ansible.com/blog/ansiblefest-nyc-video-recaps

Experiment with requirements.yml file path.

---

group_vars/international-production/main.yml
group_vars/staging/main.yml
group_vars/tag_Role_Drupal-WebApp/main.yml

See https://github.com/DoSomething/tower/blob/0ccecf9ebd3f51e9e8c6da6732c75ab54b2a6611/roles/dosomething.web/tasks/php-composer.yml.

Sets up composer automatic updates on drupal prod, intl and stage.

---

roles/dosomething.mb-node/README.md
roles/dosomething.mb-node/defaults/main.yml
roles/dosomething.mb-node/meta/main.yml

MB node role spelling fixes.

---

roles/dosomething.mb-php/README.md
roles/dosomething.mb-php/defaults/main.yml
roles/dosomething.mb-php/meta/main.yml
roles/dosomething.mb-php/tasks/apps.yml
roles/dosomething.mb-php/tasks/main.yml
roles/dosomething.mb-php/templates/mbc-transactional-email/init.conf.j2
roles/dosomething.vagrant/meta/main.yml

This PR introduces a role for Message Broker PHP server.
This isn't 100% finished and mostly serves as an example for deployment of one of such applications: mbc-transactional-email.
CC @DeeZone @sheydari-ds

MB php example app.

---

roles/dosomething.dosomething-dev/tasks/testing-utilities.yml
roles/dosomething.nodejs/defaults/main.yml
roles/dosomething.nodejs/meta/main.yml
roles/dosomething.nodejs/tasks/install.yml
roles/dosomething.nodejs/tasks/main.yml
roles/requirements.yml

Fixes #86.
```
vagrant@dev:~$ npm --version
2.11.3
```

Updates Nodejs/npm.

---

Vagrantfile

Use multiple SSH private keys: vagrant insecure and user secure.

---

nginx-lb-prod.yml
roles/dosomething.nginx-lb/tasks/main.yml

- Update Nginx LB role.
- Nginx LB role.
- Testing against EC2 instances.

Updated Nginx Playbook

---

nginx-static-prod.yml
roles/dosomething.hhvm/README.md
roles/dosomething.hhvm/meta/main.yml
roles/dosomething.hhvm/tasks/main.yml

Will test out on the Nginx Static servers first, so not touching production.

Adding HHVM role to test out on Nginx Static "Folio" site.

---

nginx-static-prod.yml
roles/dosomething.nginx-static/meta/main.yml
roles/dosomething.nginx-static/templates/nginx.conf.j2

Adds HHVM config to dosomething.nginx-static role Nginx template file.
In the dosomething.nginx-static/templates/nginx.conf.j2 file.
Manually tested on the server.
The Nginx "Static"/Folio site requires some minimum PHP parsing, and gives us a chance to test HHVM.
https://github.com/DoSomething/phoenix/issues/5434

Adding HHVM config to Nginx-Static role.

---

roles/dosomething.nginx-static/templates/nginx.conf.j2

Updated to use index.php instead of index.html for mobile app.

---

roles/dosomething.phoenix/templates/nginx/app.j2

- Fixes regexp logic error in the app nginx config
- Fixes #169 
- Fixes DoSomething/phoenix#5667

Fixes regexp logic error in the app nginx config.

---

roles/dosomething.nodejs/defaults/main.yml

Updates Nodejs version to 4.x standard.
The one line variable change.
Test on web1 in thor.
We need to upgrade Node to 4.x to fix issues with node-sass.
https://github.com/DoSomething/phoenix/issues/5770

Updating Node version to 4.x

---

roles/dosomething.phoenix-dev/tasks/testing-utilities.yml

3.6.0 fails with https://github.com/Medium/phantomjs/issues/399

Updates mocha-phantomjs to new major version.

---

roles/dosomething.vagrant/tasks/main.yml

Install NFS tools for Phoenix Vagrant.

---

northstar-mobile-commons-daemon.yml
roles/dosomething.php7/README.md
roles/dosomething.php7/defaults/main.yml
roles/dosomething.php7/handlers/main.yml
roles/dosomething.php7/meta/main.yml
roles/dosomething.php7/tasks/main.yml
roles/dosomething.php7/tasks/php-composer.yml
roles/dosomething.php7/tasks/php.yml
roles/dosomething.php7/vars/main.yml

Adding NSMCD Server setup role.

Adding PHP 7.0 Role.

---

pull_request_template.md
quasar-ansible.yml
roles/quasar.ansible/README.md
roles/quasar.ansible/meta/main.yml
roles/quasar.ansible/tasks/main.yml
roles/quasar.java/README.md
roles/quasar.java/meta/main.yml
roles/quasar.java/tasks/main.yml
roles/quasar.jenkins/README.md
roles/quasar.jenkins/meta/main.yml
roles/quasar.jenkins/tasks/main.yml

Things this PR does:
* Adds PR template.
* Adds Ansible install role.
* Adds Oracle Java 8 installer in a headless fashion.
* Adds Jenkins installer role.

Quasar Ansible

---

quasar-jenkins.yml
roles/quasar.haproxy/tasks/main.yml

* Adds Quasar Jenkins config.
* Updated HA Proxy network tuning values.
Files below.
Already tested in AWS Prod.

Adding Quasar Jenkins server config.

---

quasar-etl.yml

Breaks out each ETL node so hostname is separated successfully.
Playbook Code.
Will test it O'Reilly style.

Adding App User and breaking out each node

---

quasar-looker.yml
roles/quasar.looker/README.md
roles/quasar.looker/meta/main.yml
roles/quasar.looker/tasks/main.yml

* Adds Looker prep role for Quasar environment.
* Code below
* Will manually test in Quasar environment since we're not live with it yet.
* Moving Looker to Quasar VPC and environment as it's the last thing living in old AWS Hubble env.
https://github.com/DoSomething/quasar/issues/229

Quasar looker

---

roles/quasar.looker/tasks/main.yml

* Fixes quick syntax issue in Looker file limit sets.
* End of `quasar.looker` role tasks.
* Tested in Quasar.

Separate out Looker file limit sets.

---

quasar-looker.yml

* Fixing another stupid syntax error.

Update playbook to right host.

---

roles/dosomething.vagrant/tasks/main.yml

- add rogue connection 
- 👀 
Fixes DoSomething/phoenix/issues/7125

Add rogue setup to vagrant tasks

---

roles/quasar.etl-node/tasks/main.yml

Adds the AWS CLI package to Quasar ETL nodes.
One line file change, so right below ⬇️ 
Will test in prod.

Adding AWS CLI install package.

---

roles/quasar.etl-node/tasks/main.yml

* For Quasar ETL nodes, adds MySQL Python connector and pre-requisites.
Quasar ETL Node role.
Tested in Prod.
https://github.com/DoSomething/quasar/issues/267

Adding MySQL connection packages for Python.

---

roles/quasar.etl-node/tasks/main.yml

Adding MySQL Python 3 Support.

---

roles/dosomething.nodejs/defaults/main.yml

Updates the NodeJS version to 6.x.
After this is approved, I can update the box version for Vagrant, package and upload a new version for Atlas.
https://github.com/DoSomething/devops/issues/222

Updating Node version to 6.x

---

roles/quasar.etl-node/tasks/main.yml

* Adds `oauthlib` and `oauthlib-request` packages to Quasar ETL nodes.
* One file change, so that one.
* Manually tested via local SSH, still no good testing policy for Ansible policies, aside from QA env, which Quasar doesn't currently have.

Adding required oauthlib packages for Northstar API scraping.

---

thor-base-setup.yml

For safe testing of ansible #251
Adds a new base only step for thor environment to test out key rolling out.
This is basically the same as the production base playbook.
I'll be testing this post commit in Jenkins
DoSomething/devops#251

Add a base setup playbook for thor environment.

---

thor-sixpack.yml

For now map directly to the server pending discussion on tags and
dynamic inventory.
Adds a playbook that can be triggered by jenkins.
This is mostly no-op as the changes were tested in #219 
Run jenkins with role after submission. Then can incrementally build up playbook.

Add sixpack to thor environment

---

roles/dosomething.sixpack/tasks/main.yaml

Adds missing directory that caused build failure

Fix missing directory dependency for sixpack

---

roles/dosomething.sixpack/tasks/main.yaml
roles/dosomething.sixpack/templates/etc/systemd/system/gunicorn.service
roles/dosomething.sixpack/templates/etc/systemd/system/gunicorn.socket
roles/dosomething.sixpack/templates/etc/tmpfiles.d/gunicorn.conf

As per http://docs.gunicorn.org/en/latest/deploy.html#systemd

Wire up a simple gunicorn socket config

---

roles/dosomething.sixpack/meta/main.yaml
roles/dosomething.sixpack/tasks/main.yaml
roles/dosomething.sixpack/templates/etc/nginx/conf.d/sixpack.conf

This adds socket based nginx configuration, tested with manual playbook
triggering.
```
$ curl http://127.0.0.1:8000/
,-"-.__,-"-.__,-"-..
( C>  )( C>  )( C>  ))
/.`-_-'||`-_-'||`-_-'/
/-"-.--,-"-.--,-"-.--/|
( C>  )( C>  )( C>  )/ |
(|`-_-',.`-_-',.`-_-'/  |
`-----++-----++----'|  |
|     ||     ||     |-'
|     ||     ||     |
|     ||     ||     |
`-_-'  `-_-'  `-_-'
https://github.com/seatgeek/sixpack
```

Add nginx configuration

---

group_vars/tag_Environment_Thor/main.yml
roles/dosomething.sixpack/defaults/main.yml
roles/dosomething.sixpack/tasks/main.yaml
roles/dosomething.sixpack/templates/etc/systemd/system/gunicorn.service
roles/dosomething.sixpack/templates/sixpack.yaml.j2

Used a variable to set the redis host 

Extract sixpack_redis_host var

---

roles/dosomething.sixpack/tasks/main.yaml
roles/dosomething.sixpack/templates/etc/nginx/conf.d/sixpack.conf
roles/dosomething.sixpack/templates/etc/systemd/system/gunicorn.service
roles/dosomething.sixpack/templates/etc/systemd/system/gunicorn.socket
roles/dosomething.sixpack/templates/etc/tmpfiles.d/gunicorn.conf

Installs into virtualenv due to webassets write requirements.

Add sixpackweb support

---

roles/dosomething.sixpack/tasks/main.yaml

Fix undefined vars from refactor

---

group_vars/tag_Environment_Production/main.yml
production-sixpack.yml
roles/dosomething.sixpack/meta/main.yaml

Remove local redis in favor of elasticcache

Playbook for production sixpack server

---

group_vars/tag_Environment_Production/main.yml

Fix copy/paste error by removing extra port in sixpack prod redis host

---

roles/dosomething.web/tasks/php.yml

Add php7.1-bcmath module

---

roles/dosomething.phoenix-dev/tasks/xdebug.yml

Missing update as part of 7.1 migration, discovered rolling out to staging.

Use php-debug for 7.1

---

roles/dosomething.sixpack/tasks/main.yaml
roles/dosomething.sixpack/templates/etc/nginx/conf.d/sixpack.conf

Fix styles due to https://github.com/seatgeek/sixpack/issues/264

Fix copying of vault file

---

roles/quasar.base/vars/main.yml

Removes Nick and Jeff as SSH users in Quasar.
One file below.
Users were already removed manually in Prod.
Jeff and Nick have exited the org.

Removing Jeff and Nick as SSH users on Quasar Boxes.

---

quasar-etl-stage.yml

Sets up config for Quasar ETL staging node that is setup like Prod ETL nodes, but has self-contained Jenkins server as well.
One file below.
Will test against staging ETL box.

Added staging ETL node config.
