DoSomething/tower

- roles/dosomething.base/meta/.galaxy_install_info
- roles/dosomething.base/tasks/setup-user.yml
- roles/dosomething.dosomething-dev/meta/.galaxy_install_info
- roles/dosomething.dosomething/meta/.galaxy_install_info
- roles/dosomething.dosomething/tasks/app.yml
- roles/dosomething.search/meta/.galaxy_install_info
- roles/dosomething.web/meta/.galaxy_install_info
Fixes custom scripts available only in `bash -l`.
> Fixes scripts in ni bash. Update roles to the last version.

- group_vars/staging/app-environment.yml
On staging and prod actual builds happen outside of `$DS_APP_ROOT` folder so we don't want to hardcode its value and let `ds` script discover it by automatically.
> Removes $DS_APP_ROOT env var.

- group_vars/tag_Role_Drupal-WebApp/app-environment.yml
The Solr is running on port 8080, not 8983.
> Fixes Solr port on Drupal production.

- production.yml
- Creates shared files folder owned by `app_user`
- Manually mount shared files folder as `app_user` in order to skip fstab record
> Production: mount shared folder as app user.

- group_vars/international-production/app-environment.yml
So it gets overriden by local DB setting.
> Remove $DS_DB_MASTER_NAME var on intl prod.

- roles/dosomething.dosomething-dev/tasks/testing-utilities.yml
Latest `mocha-phantomjs` version is `4.0.0-beta1`, which requires `phantomjs2@2.0.0`.
Phantomjs2 build fails with the following error:
```
msg: npm ERR! phantomjs2@2.0.0 install:********@2.0.0 install script.
npm ERR! This is most likely a problem with the phantomjs2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs2
npm ERR! There is likely additional logging output above.
```
So I decided to lock `mocha-phantomjs` on branch `3.*` and, just to be safe, I also locked casper on `1.*`.
> Testing utilities: lock npm version.

- .gitignore
- Vagrantfile
- requirements.yml
- Changes `requirements.yml` to include only remote dependencies
- Changes `.gitignore` to ignore all roles, except own `dosomething.*` roles
- Makes vagrant automatically redownload ansible role dependencies to be compatible with Tower 2.2
> Refactors ansible role dependencies managed with requirements.yml.

- Vagrantfile
- requirements.yml
Fix for https://tower.dosomething.org/#/jobs/395/stdout:
ERROR: cannot find role in /var/lib/awx/projects/_422__tower/roles/franklinkim.nodejs
> Moves roles path to requirements.yml.

- Vagrantfile
Fixes error:
```
ERROR: cannot find role in /Users/sergii/Development/tower/roles/franklinkim.nodejs or /Users/sergii/Development/tower/franklinkim.nodejs or /opt/local/etc/ansible/roles/franklinkim.nodejs
```
> Fixes ansible galaxy requirements installation for vagrant.

- roles/dosomething.dosomething/tasks/composer.yml
> Runs composer auth task only when the token is defined.

- roles/dosomething.phoenix/templates/nginx/app.j2
Directs Nginx to send 404 errors to be parsed by Drupal instead of Nginx itself.
I am waiting for you, Vizzini! You told me to go back to the beginning!
Already tested manually in staging and thor.
We saw 404 Nginx errors on certain pages.
https://github.com/DoSomething/phoenix/issues/5298
> Adding error page directive to display app 404 page, not Nginx one.

- roles/dosomething.hhvm/tasks/main.yml
The apt_key repository keeps returning not found.
Manually run on this one of the boxes and it's working.
> Using "command" module to install apt HHVM key.

- roles/dosomething.nginx-static/tasks/main.yml
- roles/dosomething.nginx-static/templates/nginx.conf.j2
Adds config to static Nginx hosting servers to host secure version of forge.ds.org.
dosomething.nginx-static/templates/nginx.conf.j2 file.
We're doing it live!
We need to host a secure version of our forge assets to enable secure form hosting. Originally made for help.dosomething.org launch.
> Add secure site for hosting forge assets.

- ansible.cfg
- roles/dosomething.mb-php/tasks/apps.yml
- roles/dosomething.nodejs-server/defaults/main.yml
- roles/dosomething.nodejs-server/meta/main.yml
- roles/dosomething.nodejs-server/requirements.yml
- roles/dosomething.nodejs-server/tasks/main.yml
- roles/dosomething.phoenix-dev/tasks/testing-utilities.yml
- roles/dosomething.phoenix/tasks/npm.yml
- roles/dosomething.php/tasks/php.yml
- roles/dosomething.rabbitmq/tasks/install.yml
- roles/dosomething.search/tasks/main.yml
- roles/dosomething.web/tasks/php.yml
- roles/requirements.yml
A list of v2.0-related changes:
- `ansible.cfg` doesn't support executable with arguments anymore, but with 2.0 we don't need it
- `apt_key` MUST be declared before `apt_repository`
- `with_items` only support list merge using string substituion
Ubuntu-related changes:
- `ubuntu/trusty64` is updated to `20160311.0.0`
- `java7-jdk` package doesn't exist. It was succeeded by `openjdk-7-jdk`.
Other changes:
- `franklinkim.pm2` was renamed to `weareinteractive.pm2`
- `weareinteractive.pm2` dependency is replaced with our own simple implementation because of the incompatibility
> Fixes Ansible 2.0 compatibility.

- roles/dosomething.base/tasks/setup-devops-users.yml
- roles/dosomething.db/tasks/main.yml
- roles/dosomething.mb-node/tasks/apps.yml
- roles/dosomething.mb-php/tasks/apps.yml
- roles/dosomething.phoenix/tasks/configure-env.yml
- roles/dosomething.php/tasks/php.yml
- roles/dosomething.rabbitmq/tasks/configure.yml
- roles/dosomething.rabbitmq/tasks/install.yml
- roles/dosomething.search/tasks/solr-install-core.yml
- roles/dosomething.web/tasks/php.yml
Fixes deprecation warning:
```
[DEPRECATION WARNING]: Using bare variables is deprecated. Update your
playbooks so that the environment value uses the full variable syntax
('{{mb_php_apps}}'). This feature will be removed in a future release.
```
> Fixes warning "Using bare variables is deprecated".

- roles/dosomething.rabbitmq/tasks/configure.yml
Fixes an error introduced in #176. Second argument to `with_subelements` is a key, not variable.
> Fixes an error in `with_subelements`.

- quasar-haproxy.yml
- roles/quasar.haproxy/README.md
- roles/quasar.haproxy/meta/main.yml
- roles/quasar.haproxy/tasks/main.yml
Adds HA Proxy server install and playbook for Quasar environment.
The quasar.haproxy role.
Already tested in Quasar AWS environment.
> Adding HA Proxy Server Setup for Quasar.

- roles/quasar.etl-node/tasks/main.yml
* Adds `psycopg2` PostgresSQL connector to Quasar ETL nodes.
* The one line add below.
* Testing it LIVE!
* We have the choice of SQL Alchemy Redshift or Psycopg2 to connect to PostgreSQL. Including both.
> Adding PostgreSQL connector for ETL nodes to connect to

- roles/quasar.etl-node/tasks/main.yml
Adds PostgreSQL CLI client to ETL node role to allow bash scripting to RedShift.
One line addition!
Already tested in Prod.
> Adding PostgreSQL client to ETL nodes for bash scripts.

- files/devops_users/pnasrat-authorized_keys
- group_vars/all/main.yml
- roles/quasar.base/files/pnasrat-id_rsa.pub
- roles/quasar.base/vars/main.yml
Fixes DoSomething/devops#249
Adds ssh keys and user accounts for pnasrat to allow for initial end to end testing of ansible setup.
> Add pnasrat as devops user.

- roles/quasar.base/tasks/main.yml
Fixes a bug in Ansible Quuasar base role that doesn't take into account condition for Prod user existing after first creation task to create SSH dirs and keys.
The two lines below!
Manually tested against Quasar box.
> Adding var check to Prod user.

- roles/dosomething.nodejs/tasks/install.yml
Fixes #220 by using ubuntu keyserver due to lack of SNI support.
Changes the keyserver to import the package signing key to be ubuntu keyserver due to unsupported SNI on the nodesource servers.
You can change vagrant.yml:
```diff
diff --git a/vagrant.yml b/vagrant.yml
index 080331d..3012a6f 100644
--- a/vagrant.yml
+++ b/vagrant.yml
@@ -3,4 +3,4 @@
- name: Setup vagrant
hosts: all
roles:
-    - { role: dosomething.vagrant }
+    - { role: dosomething.nodejs }
```
Run `vagrant destroy && vagrant up`
Observe successful run
```
changed: [default] => {"cache_update_time": 1490025344, "cache_updated": false, "changed": true, "stderr": "", "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nThe following NEW packages will be installed:\n  nodejs\n0 …
```
> Change keyserver for nodejs key

- thor-sixpack.yml
Refactors new sixpack ansible configuration to use role sixpack server in thor env via tags. You can confirm my syntax via ansible command line
```
ansible -i /etc/ansible/ec2.py -m ping 'tag_Environment_Thor:&tag_Role_Sixpack' --list-hosts
hosts (1):
172.20.100.38
```
> Configure thor sixpack server using tags

- roles/dosomething.base/tasks/configure-system.yml
- roles/dosomething.sixpack/tasks/main.yaml
Add a raw step to enable 16.04 builds from AMI/image to work.
Ensure systemd dependencies work for sixpack.
I tested with vagrant destroy, the following vagrant changes to use 16.04 (and make it not use all memory on my laptop) and vagrant up - then curl localhost:8000 on the box.
```diff
diff --git a/Vagrantfile b/Vagrantfile
index afbb19e..cb5a0c5 100644
--- a/Vagrantfile
+++ b/Vagrantfile
@@ -1,10 +1,10 @@
Vagrant.configure("2") do |config|
-  config.vm.box = "ubuntu/trusty64"
+  config.vm.box = "bento/ubuntu-16.04"
config.vm.provider "virtualbox" do |v|
-    v.customize ["modifyvm", :id, "--memory", 3072]
+    v.customize ["modifyvm", :id, "--memory", 2048]
v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
end
diff --git a/vagrant.yml b/vagrant.yml
index 080331d..9840402 …
```
> Fix dependencies for ansible and sixpack

- roles/dosomething.vagrant/meta/main.yml
Allows local vagrant build to work by disabling sixpack on trusty.
We should discuss moving to 16.04 and what are the issues/concerns for that.
> For vagrant builds only install sixpack on xenial

- staging.yml
When trying to deploy @mirie ssh key to staging I noticed the ansible run succeeded but had no hosts
```
PLAYBOOK: staging.yml **********************************************************
1 plays in /var/lib/jenkins/jobs/Ansible Repo Checkout/workspace/staging.yml
PLAY [Setup Staging Server] ****************************************************
skipping: no hosts matched
```
> Use tag to identify staging box

- roles/dosomething.phoenix-dev/tasks/xdebug.yml
Error now due to ini file not being enabled. This should create the necessary link
> Enable xdebug via symlink

- quasar-etl-stage.yml
Bare Ubuntu 16.04 boxes need Python2 installed. This sets it as a pre-step for Quasar-Stage-ETL.
One file below.
Will test on stage box.
> Added Python2 install pre-step.
